/**
 * pt → en for the `facilities`/`hazards` tags of src/lib/spots.ts.
 *
 * The arrays are written in Portuguese and were being rendered verbatim in the
 * EN UI («Estacionamento», «Correntes fortes»…). This dictionary is the single
 * translation source: the EN UI maps each tag through `spotTagEn`, and the
 * audit in spotDescriptions.test.ts enforces that EVERY token has an entry
 * (and no entry is a dead key).
 *
 * Proper nouns / brands / loanwords keep the original — they live in
 * `SPOT_TAG_IDENTITY` so the audit's «never a verbatim copy» rule allows them.
 */

export const SPOT_TAG_EN: Record<string, string> = {
  // ── facilities ──────────────────────────────────────────────────────────
  '5 Cable Parks': '5 cable parks',
  'Acesso íngreme': 'Steep access',
  Alojamento: 'Accommodation',
  Aluguer: 'Rental',
  'Apoio de praia': 'Beach support',
  'Bar de praia (verão)': 'Beach bar (summer)',
  Barco: 'Boat',
  'Barco para a ilha': 'Boat to the island',
  'Barco-táxi': 'Water taxi',
  'Cable 2.0': 'Cable 2.0',
  'Cable park': 'Cable park',
  Café: 'Café',
  Camping: 'Camping',
  Casino: 'Casino',
  'Clube Nautico': 'Nautical club',
  Comboio: 'Train',
  Escola: 'School',
  'Escola de surf': 'Surf school',
  'Escola foil': 'Foil school',
  'Escola kite': 'Kite school',
  'Escola surf': 'Surf school',
  'Escola wake': 'Wake school',
  'Escola windsurf': 'Windsurf school',
  Escolas: 'Schools',
  'Escolas foil': 'Foil schools',
  'Escolas kite': 'Kite schools',
  'Escolas kite e surf': 'Kite and surf schools',
  'Escolas na zona': 'Schools in the area',
  'Escolas surf': 'Surf schools',
  'Escolas windsurf': 'Windsurf schools',
  'Escolas wing foil': 'Wing foil schools',
  Estacionamento: 'Parking',
  'Estacionamento limitado': 'Limited parking',
  Farol: 'Lighthouse',
  'FeelViana Sport Hotel': 'FeelViana Sport Hotel',
  Ferry: 'Ferry',
  'Ferry Setúbal': 'Setúbal ferry',
  Hotel: 'Hotel',
  Hotéis: 'Hotels',
  Marina: 'Marina',
  Metro: 'Metro',
  'Moinhos de vento': 'Windmills',
  'Parque de merendas': 'Picnic area',
  'Piscina de Mares': 'Piscina de Mares',
  'Piscinas municipais': 'Municipal pools',
  'Praia fluvial': 'River beach',
  Restaurante: 'Restaurant',
  Restaurantes: 'Restaurants',
  'Salva-vidas': 'Lifeguards',
  'Salva-vidas (época balnear)': 'Lifeguards (bathing season)',
  Snackbar: 'Snack bar',
  'Taxi-boat Melres': 'Taxi-boat Melres',
  Teleski: 'Teleski',
  WC: 'WC',
  'Wake Boat': 'Wake boat',

  // ── hazards ─────────────────────────────────────────────────────────────
  'Acesso de barco apenas': 'Boat access only',
  'Acesso difícil': 'Difficult access',
  'Acesso estreito': 'Narrow access',
  'Acesso limitado': 'Limited access',
  'Acesso por barco': 'Access by boat',
  'Acesso por barco/pontão': 'Access by boat/pontoon',
  'Acesso por estrada de pinhal': 'Access via pine forest road',
  'Acesso por estrada de terra': 'Dirt road access',
  'Acesso por estrada íngreme': 'Steep road access',
  'Acesso por molhe': 'Access via breakwater',
  'Acesso por trilhos': 'Access via trails',
  'Balsa de barcos': 'Boat ferry',
  'Bancos de areia': 'Sandbanks',
  'Bancos de areia com maré': 'Tidal sandbanks',
  'Bancos de areia mutáveis': 'Shifting sandbanks',
  'Bancos de areia na maré baixa': 'Sandbanks at low tide',
  Banhistas: 'Bathers',
  'Banhistas no verão': 'Bathers in summer',
  Barcos: 'Boats',
  'Barcos de pesca': 'Fishing boats',
  'Barcos na albufeira': 'Boats on the reservoir',
  'Calhau rolado': 'Rounded pebbles',
  'Conchas no fundo': 'Shells on the bottom',
  'Corredores de barcos': 'Boat lanes',
  'Corrente do Tejo': 'Tagus current',
  'Corrente em maré viva': 'Spring tide current',
  'Corrente na foz': 'Current at the river mouth',
  'Corrente na foz do Sado': 'Current at the Sado mouth',
  'Corrente na foz do Tejo': 'Current at the Tagus mouth',
  Correntes: 'Currents',
  'Correntes com swell': 'Currents with swell',
  'Correntes de maré': 'Tidal currents',
  'Correntes do Tejo': 'Tagus currents',
  'Correntes em alguns picos': 'Currents at some peaks',
  'Correntes fortes': 'Strong currents',
  'Correntes moderadas': 'Moderate currents',
  'Correntes na barra': 'Currents at the bar',
  'Correntes na foz': 'Currents at the river mouth',
  'Correntes na foz do rio': 'Currents at the river mouth',
  'Correntes na maré vazante': 'Currents on the ebb tide',
  'Correntes na saída': 'Currents at the exit',
  'Correntes no Douro': 'Douro currents',
  'Escadaria íngreme': 'Steep staircase',
  'Estruturas industriais no fundo': 'Industrial structures underwater',
  'Exposição ao vento': 'Wind exposure',
  'Exposto ao vento': 'Exposed to wind',
  Falésias: 'Cliffs',
  'Falésias no fundo — vento sideshore': 'Cliffs at the bottom — sideshore wind',
  'Fundos lamacentos': 'Muddy bottom',
  'Infraestrutura balnear Jun–Set': 'Beach facilities Jun–Sep',
  Isolamento: 'Isolation',
  'Kite restrito na época balnear': 'Kite restricted in bathing season',
  'Kitesurf proibido 1 Jun–30 Sep': 'Kitesurf banned Jun 1–Sep 30',
  'Kitesurf proibido no verão': 'Kitesurf banned in summer',
  Locals: 'Locals',
  'Locals agressivos': 'Aggressive locals',
  'Mar agitado': 'Rough sea',
  Mare: 'Tide',
  Maré: 'Tide',
  'Maré alta pode subir a lagoa': 'High tide can flood the lagoon',
  'Maré baixa': 'Low tide',
  'Maré baixa expõe areia': 'Low tide exposes sand',
  'Maré baixa expõe bancos de areia': 'Low tide exposes sandbanks',
  'Menos infraestrutura que Caparica': 'Less infrastructure than Caparica',
  Molhe: 'Breakwater',
  'Multidao no verao': 'Summer crowds',
  Multidão: 'Crowds',
  'Multidão de iniciantes': 'Crowds of beginners',
  'Multidão de verão': 'Summer crowds',
  'Multidão de verão na vila (não na praia)': 'Summer crowds in town (not on the beach)',
  'Multidão de verão na zona balnear': 'Summer crowds in the bathing area',
  'Multidão em dias de evento': 'Crowds on event days',
  'Multidão em eventos': 'Crowds at events',
  'Multidão extrema': 'Extreme crowds',
  'Multidão extrema no verão': 'Extreme summer crowds',
  'Multidão na época alta': 'Crowds in high season',
  'Multidão no verão': 'Summer crowds',
  'Multidão nos fins de semana': 'Weekend crowds',
  'Nortada irregular': 'Irregular north wind',
  'Ondas gigantes no inverno': 'Giant winter waves',
  'Ondas gigantescas': 'Huge waves',
  'Ondas irregulares': 'Irregular waves',
  'Ondas mortais': 'Deadly waves',
  'Ondas pesadas': 'Heavy waves',
  'Ondas potentes': 'Powerful waves',
  'Ondas rápidas': 'Fast waves',
  'Ondas tubulares': 'Tubular waves',
  'Outros riders': 'Other riders',
  'Paredão perigoso': 'Dangerous seawall',
  'Pedras entre Cabedelo e Amorosa': 'Rocks between Cabedelo and Amorosa',
  'Pedras na maré baixa': 'Rocks at low tide',
  'Pouco profundo': 'Shallow',
  'Praia pequena': 'Small beach',
  'Quedas de falésia': 'Cliff falls',
  'Reef raso': 'Shallow reef',
  Ressaca: 'Rip current',
  'Ressaca forte': 'Strong rip current',
  'Restrições de kite na época balnear': 'Kite restrictions in bathing season',
  'Restrições de kite no verão (época balnear)': 'Kite restrictions in summer (bathing season)',
  'Restrições na época balnear': 'Restrictions in bathing season',
  'Rocha vulcânica afiada': 'Sharp volcanic rock',
  'Rocha vulcânica rasa': 'Shallow volcanic rock',
  Rochas: 'Rocks',
  'Rochas afiadas': 'Sharp rocks',
  'Rochas em maré baixa': 'Rocks at low tide',
  'Rochas junto ao forte': 'Rocks by the fort',
  'Rochas junto ao molhe': 'Rocks by the breakwater',
  'Rochas na extremidade sul': 'Rocks at the south end',
  'Rochas na lagoa': 'Rocks in the lagoon',
  'Rochas na maré baixa': 'Rocks at low tide',
  'Rochas na praia oceânica adjacente': 'Rocks on the adjacent ocean beach',
  'Rochas nas extremidades': 'Rocks at the ends',
  'Rochas nas pontas': 'Rocks at the points',
  'Rochas no fundo': 'Rocks on the bottom',
  'Rochas no lançamento': 'Rocks at the launch',
  'Rochas no leito': 'Rocks on the riverbed',
  'Rochas no reef': 'Rocks on the reef',
  'Rochas submersas': 'Submerged rocks',
  'Rochas vulcânicas': 'Volcanic rocks',
  'Sem escola de kite na praia': 'No kite school on the beach',
  'Sem infraestrutura': 'No infrastructure',
  'Sem infraestruturas': 'No infrastructure',
  'Sem vigilância': 'No lifeguards',
  'Tráfego de barcos': 'Boat traffic',
  'Tráfego de barcos na foz': 'Boat traffic at the river mouth',
  'Tráfego de barcos na ria': 'Boat traffic on the ria',
  'Tráfego de iniciantes': 'Beginner traffic',
  'Tráfego fluvial': 'River traffic',
  'Tráfego marítimo': 'Maritime traffic',
  'Tráfego na época alta': 'High-season traffic',
  'Vento forte': 'Strong wind',
  'Vento forte no verão': 'Strong summer wind',
  'Vento gusty junto ao porto': 'Gusty wind by the harbour',
  'Vento irregular junto à foz': 'Irregular wind by the river mouth',
  'Vento pode desligar de repente': 'Wind can drop suddenly',
  'Zona portuária': 'Harbour area',
  'Zonas de proteção da reserva': 'Reserve protection zones',
  'Água fria': 'Cold water',
  'Água fria (17-20°C)': 'Cold water (17–20°C)',
  'Água pode cheirar mal': 'Water can smell bad',
  'Água quente junto à costa': 'Warm water near the coast',
};

/**
 * Tokens whose EN entry is intentionally identical (proper nouns, brands and
 * loanwords already used in English) — the audit allows these to keep the
 * original spelling.
 */
export const SPOT_TAG_IDENTITY = new Set([
  '5 Cable Parks',
  'Cable 2.0',
  'Cable park',
  'Café',
  'Camping',
  'Casino',
  'FeelViana Sport Hotel',
  'Ferry',
  'Hotel',
  'Locals',
  'Marina',
  'Metro',
  'Piscina de Mares',
  'Taxi-boat Melres',
  'Teleski',
  'Wake Boat',
  'WC',
]);

/** Translate a facility/hazard tag for the EN UI; unknown tokens keep the PT. */
export function spotTagEn(tag: string): string {
  return SPOT_TAG_EN[tag] ?? tag;
}
