-- ============================================================
-- VenTu — subscribe_alert RPC
--
-- SUPERSEDED (S2 / H2). Re-run this file only to REMOVE the old relay:
-- it used to create an anonymous subscribe_alert whose rate limit was a
-- caller-controlled `client_id` (trivially rotated) and whose verify_token
-- came from the caller — the combination turned VenTu into an email relay
-- (unlimited pending rows → one verification email per row per day to any
-- address the attacker chose).
--
-- The write path is now, in this order:
--   1. supabase/supabase-rate-limit-common.sql        (request_client_ip / check_rate_limit)
--   2. supabase/supabase-alerts-harden-legacy.sql     (per-IP limit, server-generated
--      token, ≤5 pending rows per address, UNIQUE (lower(email), spot_slug, sport)
--      while active, anon grants revoked)
--
-- Drop the weak 7-arg signature (client-supplied verify_token): neither this
-- file nor a stale install may re-create it. The hardened RPC is also 6-arg,
-- so only the 7-arg one is dropped here — run
-- supabase-alerts-harden-legacy.sql to install (or reinstall) the write path.
-- ============================================================

DROP FUNCTION IF EXISTS public.subscribe_alert(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT);
