import { defineConfig } from 'vitest/config'
import path from 'path'

export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'src/**/*.test.ts',
      'scripts/lib/__tests__/ecowitt.normalize.test.js',
      'scripts/lib/__tests__/metar.test.js',
      'scripts/lib/__tests__/windBlend.test.js',
      'scripts/lib/__tests__/htmlEscape.test.js',
      'scripts/lib/__tests__/analyzeScoreFeedback.test.js',
      'scripts/lib/__tests__/ipma.test.js',
      'scripts/lib/__tests__/spamFilter.test.js',
      'scripts/lib/__tests__/safeUrl.test.js',
      'scripts/lib/__tests__/fetchRss.test.js',
      'scripts/lib/__tests__/fetchIHTides.test.js',
      'scripts/lib/__tests__/forecastConfidence.test.js',
      'scripts/lib/__tests__/ihBuoys.test.js',
      'scripts/lib/__tests__/ihApiKeyTest.test.js',
      'scripts/lib/__tests__/buoyBias.test.js',
      'scripts/lib/__tests__/dawnPatrolScore.test.js',
      'scripts/lib/__tests__/meteoalarmApiKeyTest.test.js',
      'scripts/lib/__tests__/ipmaWarnings.test.js',
      'scripts/lib/__tests__/copernicusBuoys.test.js',
      'scripts/lib/__tests__/meteoalarmWarnings.test.js',
      'scripts/lib/__tests__/ipmaRadar.test.js',
      'scripts/lib/__tests__/modelHealth.test.js',
      'scripts/lib/__tests__/updateSchedule.test.js',
      'scripts/lib/__tests__/ihObservedTide.test.js',
      'scripts/lib/__tests__/contributionsPrivacy.test.js',
      'scripts/lib/__tests__/terraformExpressions.test.js',
      'scripts/lib/__tests__/forecastSkill.test.js',
      'scripts/lib/__tests__/updateConditions.test.js',
      'scripts/lib/__tests__/buoyCoherence.test.js',
      'scripts/lib/__tests__/observedWaveMerge.test.js',
      'scripts/lib/__tests__/wmoBiasArchive.test.js',
      'scripts/lib/__tests__/waveBiasGate.test.js',
      'scripts/lib/__tests__/fetchWaveBias.test.js',
      'scripts/lib/__tests__/mergeWaveBias.test.js',
      'scripts/lib/__tests__/buoyCoherenceArchive.test.js',
      'scripts/lib/__tests__/buoyCoherenceDaily.test.js',
      'scripts/lib/__tests__/windBiasArchive.test.js',
      'scripts/lib/__tests__/skillRegression.test.js',
      'scripts/lib/__tests__/buoyLayerHealth.test.js',
      'scripts/lib/__tests__/observedWaveNazareE2E.test.js',
      'scripts/lib/__tests__/ihIsobaths.test.js',
      'scripts/lib/__tests__/ihCoastalWarnings.test.js',
      'scripts/lib/__tests__/verifyMeteoalarmWarnings.test.js',
      'scripts/lib/__tests__/meteoalarmChainE2E.test.js',
      'scripts/lib/__tests__/verifyIhBuoyLayer.test.js',
      'scripts/lib/__tests__/checkBuoyLayerHealth.test.js',
      'scripts/lib/__tests__/dataLayerHealth.test.js',
      'scripts/lib/__tests__/ecowittApiKeyTest.test.js',
      'scripts/lib/__tests__/resendApiKeyTest.test.js',
      'scripts/lib/__tests__/checkCitationCff.test.js',
      'scripts/lib/__tests__/coastalWarningsArchive.test.js',
      'scripts/lib/__tests__/coastalWarningsFetchES.test.js',
    ],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
