import { getTranslation } from '@/lib/i18n'
import { Wind, Waves, Database, Brain, Code, Heart, Globe, Zap, Shield } from 'lucide-react'

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params
  const isPt = locale === 'pt'

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      <div className="text-center space-y-4">
        <Wind className="w-16 h-16 text-ocean-400 mx-auto" />
        <h1 className="text-4xl font-bold text-white/90">
          {isPt ? 'Sobre o WindSpot' : 'About WindSpot'}
        </h1>
        <p className="text-xl text-white/60 max-w-2xl mx-auto">
          {isPt
            ? 'Uma plataforma open-source dedicada aos desportos náuticos em Portugal'
            : 'An open-source platform dedicated to water sports in Portugal'}
        </p>
      </div>

      <div className="glass-card p-8 space-y-6">
        <h2 className="text-2xl font-bold text-white/90">
          {isPt ? 'A Nossa Missão' : 'Our Mission'}
        </h2>
        <p className="text-white/70 leading-relaxed">
          {isPt
            ? 'O WindSpot nasceu da necessidade de ter uma plataforma centralizada, gratuita e de código aberto para todos os praticantes de desportos náuticos em Portugal. Queremos democratizar o acesso à informação meteorológica marítima e criar uma comunidade forte em torno do surf, kitesurf, windsurf e big wave.'
            : 'WindSpot was born from the need to have a centralized, free and open-source platform for all water sports practitioners in Portugal. We want to democratize access to marine weather information and create a strong community around surf, kitesurf, windsurf and big wave.'}
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6 text-center space-y-4">
          <Database className="w-10 h-10 text-wave-400 mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'Dados em Tempo Real' : 'Real-time Data'}</h3>
          <p className="text-sm text-white/60">
            {isPt ? 'Open-Meteo Marine API com atualizações a cada 3 horas' : 'Open-Meteo Marine API with updates every 3 hours'}
          </p>
        </div>
        <div className="glass-card p-6 text-center space-y-4">
          <Brain className="w-10 h-10 text-wind-400 mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'IA Automatizada' : 'Automated AI'}</h3>
          <p className="text-sm text-white/60">
            {isPt ? 'Notícias geradas por Gemini Flash com resumos inteligentes' : 'News generated by Gemini Flash with smart summaries'}
          </p>
        </div>
        <div className="glass-card p-6 text-center space-y-4">
          <Code className="w-10 h-10 text-surf-400 mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'Código Aberto' : 'Open Source'}</h3>
          <p className="text-sm text-white/60">
            {isPt ? 'MIT License. Contribuições bem-vindas!' : 'MIT License. Contributions welcome!'}
          </p>
        </div>
      </div>

      <div className="glass-card p-8 space-y-6">
        <h2 className="text-2xl font-bold text-white/90">
          {isPt ? 'Tecnologias Utilizadas' : 'Technologies Used'}
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { icon: <Zap className="w-6 h-6" />, name: 'Next.js 14', desc: 'React Framework' },
            { icon: <Wind className="w-6 h-6" />, name: 'Tailwind CSS', desc: 'Styling' },
            { icon: <Waves className="w-6 h-6" />, name: 'Recharts', desc: 'Charts' },
            { icon: <Globe className="w-6 h-6" />, name: 'Open-Meteo', desc: 'Marine API' },
            { icon: <Brain className="w-6 h-6" />, name: 'Gemini Flash', desc: 'AI News' },
            { icon: <Shield className="w-6 h-6" />, name: 'TypeScript', desc: 'Type Safety' },
          ].map((tech, i) => (
            <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-white/5">
              <div className="text-ocean-400">{tech.icon}</div>
              <div>
                <p className="text-sm font-medium">{tech.name}</p>
                <p className="text-xs text-white/50">{tech.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="text-center space-y-4">
        <p className="flex items-center justify-center gap-2 text-white/50">
          <Heart className="w-5 h-5 text-red-400" />
          {isPt ? 'Feito com paixão pela comunidade náutica portuguesa' : 'Made with passion for the Portuguese nautical community'}
        </p>
        <a
          href="https://github.com/braindeadpt/windspot-pt"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl font-medium transition-all border border-white/10"
        >
          <Code className="w-5 h-5" />
          {isPt ? 'Contribuir no GitHub ↗' : 'Contribute on GitHub ↗'}
        </a>
      </div>
    </div>
  )
}
