import { Wind, Waves, Database, Brain, Code, Heart, Globe, Zap, Shield } from 'lucide-react'
import PageHeader from '@/components/ui/PageHeader'
import Button from '@/components/ui/Button'
import { buildPageMetadata } from '@/lib/seo'
import { pipelineSchedule } from '@/lib/dataPipelineSchedule'
import { loadForecastSkillBuoys } from '@/lib/forecastSkill'
import WaveBiasSection from '@/components/spots/WaveBiasSection'
import CoherenceTrendSection from '@/components/spots/CoherenceTrendSection'
import type { Metadata } from 'next'

const sign = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(2)}`
const two = (n: number | null | undefined) => (n == null ? '—' : n.toFixed(2))


export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  const isPt = locale === 'pt'
  const loc = isPt ? 'pt' : 'en'

  return buildPageMetadata({
    title: isPt ? 'Sobre — VenTu' : 'About — VenTu',
    description: isPt
      ? 'Plataforma open-source de condições náuticas em Portugal — missão, dados e como contribuir.'
      : 'Open-source water sports conditions platform for Portugal — mission, data and how to contribute.',
    locale: loc,
    path: `/${loc}/about/`,
  })
}

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params
  const isPt = locale === 'pt'

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      <PageHeader
        align="center"
        icon={<Wind className="w-16 h-16 text-data-waves" aria-hidden />}
        title={isPt ? 'Sobre o VenTu' : 'About VenTu'}
        subtitle={
          isPt
            ? 'Uma plataforma open-source dedicada aos desportos náuticos em Portugal'
            : 'An open-source platform dedicated to water sports in Portugal'
        }
      />

      <div className="card-1 p-8 space-y-6">
        <h2 className="text-2xl font-bold text-fg">
          {isPt ? 'A Nossa Missão' : 'Our Mission'}
        </h2>
        <p className="text-fg-muted leading-relaxed">
          {isPt
            ? 'O VenTu nasceu da necessidade de ter uma plataforma centralizada, gratuita e de código aberto para todos os praticantes de desportos náuticos em Portugal. Queremos democratizar o acesso à informação meteorológica marítima e criar uma comunidade forte em torno do surf, kitesurf, windsurf e big wave.'
            : 'VenTu was born from the need to have a centralized, free and open-source platform for all water sports practitioners in Portugal. We want to democratize access to marine weather information and create a strong community around surf, kitesurf, windsurf and big wave.'}
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="card-1 p-6 text-center space-y-4">
          <Database className="w-10 h-10 text-data-waves mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'Dados Actualizados' : 'Updated Data'}</h3>
          <p className="text-sm text-fg-muted">
            {isPt
              ? `Open-Meteo — previsões ${pipelineSchedule('pt')} (ensemble multi-modelo de ondas e vento)`
              : `Open-Meteo — forecasts ${pipelineSchedule('en')} (multi-model wave & wind ensemble)`}
          </p>
        </div>
        <div className="card-1 p-6 text-center space-y-4">
          <Brain className="w-10 h-10 text-data-wind mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'IA Automatizada' : 'Automated AI'}</h3>
          <p className="text-sm text-fg-muted">
            {isPt ? 'Notícias geradas por Gemini Flash com resumos inteligentes' : 'News generated by Gemini Flash with smart summaries'}
          </p>
        </div>
        <div className="card-1 p-6 text-center space-y-4">
          <Code className="w-10 h-10 text-data-waves mx-auto" />
          <h3 className="text-lg font-semibold">{isPt ? 'Código Aberto' : 'Open Source'}</h3>
          <p className="text-sm text-fg-muted">
            {isPt ? 'MIT License. Contribuições bem-vindas!' : 'MIT License. Contributions welcome!'}
          </p>
        </div>
      </div>

      <div className="card-1 p-8 space-y-6">
        <h2 className="text-2xl font-bold text-fg">
          {isPt ? 'Tecnologias Utilizadas' : 'Technologies Used'}
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { icon: <Zap className="w-6 h-6" />, name: 'Next.js 16', desc: 'React Framework' },
            { icon: <Wind className="w-6 h-6" />, name: 'Tailwind CSS', desc: 'Styling' },
            { icon: <Waves className="w-6 h-6" />, name: 'Leaflet', desc: 'Interactive maps' },
            { icon: <Globe className="w-6 h-6" />, name: 'Open-Meteo', desc: 'Marine + Weather API' },
            { icon: <Wind className="w-6 h-6" />, name: 'IPMA · Ecowitt', desc: isPt ? 'Observações' : 'Observations' },
            { icon: <Brain className="w-6 h-6" />, name: 'Gemini Flash', desc: 'AI News' },
            { icon: <Shield className="w-6 h-6" />, name: 'Supabase', desc: 'Contributions' },
          ].map((tech, i) => (
            <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-surface-1/[0.04]">
              <div className="text-data-waves">{tech.icon}</div>
              <div>
                <p className="text-sm font-medium">{tech.name}</p>
                <p className="text-xs text-fg-muted">{tech.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="card-1 p-8 space-y-4">
        <h2 className="text-2xl font-bold text-fg">
          {isPt ? 'Imagens, dados e atribuição' : 'Imagery, data & attribution'}
        </h2>
        <ul className="text-sm text-fg-muted space-y-2 list-disc pl-5">
          <li>
            {isPt ? (
              <>
                Previsões:{' '}
                <a href="https://open-meteo.com/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  Weather data by Open-Meteo.com
                </a>{' '}
                (licença{' '}
                <a href="https://creativecommons.org/licenses/by/4.0/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  CC BY 4.0
                </a>
                ) — ensemble multi-modelo: ondas por{' '}
                <a href="https://www.dwd.de/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  DWD EWAM
                </a>{' '}
                e{' '}
                <a href="https://www.ecmwf.int/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  ECMWF WAM
                </a>{' '}
                (CC-BY), NOAA GFS Wave/GWAM; vento por DWD ICON-EU, ECMWF IFS, GFS e Météo-France.
              </>
            ) : (
              <>
                Forecasts:{' '}
                <a href="https://open-meteo.com/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  Weather data by Open-Meteo.com
                </a>{' '}
                (licence{' '}
                <a href="https://creativecommons.org/licenses/by/4.0/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  CC BY 4.0
                </a>
                ) — multi-model ensemble: waves by{' '}
                <a href="https://www.dwd.de/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  DWD EWAM
                </a>{' '}
                and{' '}
                <a href="https://www.ecmwf.int/" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  ECMWF WAM
                </a>{' '}
                (CC-BY), NOAA GFS Wave/GWAM; wind by DWD ICON-EU, ECMWF IFS, GFS and Météo-France.
              </>
            )}
          </li>
          <li>
            {isPt ? (
              <>
                Citação oficial:{' '}
                <em className="not-italic">Zippenfenig, P. (2023). Open-Meteo.com Weather API [Computer software].</em>{' '}
                Zenodo.{' '}
                <a href="https://doi.org/10.5281/zenodo.7970649" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  https://doi.org/10.5281/zenodo.7970649
                </a>
                .
              </>
            ) : (
              <>
                Official citation:{' '}
                <em className="not-italic">Zippenfenig, P. (2023). Open-Meteo.com Weather API [Computer software].</em>{' '}
                Zenodo.{' '}
                <a href="https://doi.org/10.5281/zenodo.7970649" className="underline hover:text-fg transition-colors" target="_blank" rel="noopener noreferrer">
                  https://doi.org/10.5281/zenodo.7970649
                </a>
                .
              </>
            )}
          </li>
          <li>
            {isPt
              ? 'Miniaturas dos spots: export Esri World Imagery nas coordenadas reais de cada praia (nunca stock genérico a fingir ser o spot).'
              : 'Spot thumbnails: Esri World Imagery export at each beach’s real coordinates (never generic stock pretending to be the spot).'}
          </li>
          <li>
            <strong className="text-fg">Imagery © Esri, Maxar, Earthstar Geographics</strong>
          </li>
          <li>
            {isPt
              ? 'Fotos de ambiente por região (home, explorar, sobre): Unsplash e Pexels — licença livre para uso comercial. Lista em public/images/CREDITS.md.'
              : 'Regional lifestyle photos (home, explore, about): Unsplash and Pexels — free for commercial use. See public/images/CREDITS.md.'}
          </li>
          <li>
            {isPt ? (
              <>
                Todas as fontes, licenças e atribuições numa só página:{' '}
                <a href={`/${locale}/fontes/`} className="underline hover:text-fg transition-colors">
                  Fontes de dados
                </a>
                .
              </>
            ) : (
              <>
                Every source, licence and attribution in one page:{' '}
                <a href={`/${locale}/fontes/`} className="underline hover:text-fg transition-colors">
                  Data sources
                </a>
                .
              </>
            )}
          </li>
        </ul>
      </div>

      {(() => {
        const skill = loadForecastSkillBuoys()
        if (!skill.hasData) return null
        const byOrigin = skill.byOrigin ?? { ih: null, 'wmo-es': null }
        const originLabel = (o: string | undefined) =>
          o === 'ih' ? 'IH' : o === 'wmo-es' ? 'WMO-ES' : '—'
        return (
          <div className="card-1 p-8 space-y-4">
            <h2 className="text-2xl font-bold text-fg">
              {isPt ? 'Skill real do forecast por boia' : 'Real forecast skill per buoy'}
            </h2>
            <p className="text-sm text-fg-muted leading-relaxed">
              {isPt ? (
                <>Skill <em className="not-italic text-fg">real</em> do forecast — a previsão best_match feita no run N para a hora H é comparada com a leitura da boia para H quando chega (lead time &gt; 0), acumulado run a run em <code className="text-fg">forecast-skill.json</code>. <strong className="text-fg">ME = média(observado − previsão)</strong>: positivo significa que o modelo subestima a onda. Distinto do viés ERA5 acima — isto é o quão bom o forecast é, não o quão enviesado o modelo de reanálise está. As stats são separadas por plataforma: <strong className="text-fg">IH</strong> (boias Datawell, com chave) vs <strong className="text-fg">WMO-ES</strong> (Copernicus, sem chave) — o total misto esconde como cada uma se comporta.</>
              ) : (
                <>Real forecast skill — the best_match forecast made in run N for hour H is compared with the buoy reading for H once it arrives (lead time &gt; 0), accumulated run after run in <code className="text-fg">forecast-skill.json</code>. <strong className="text-fg">ME = mean(observed − forecast)</strong>: positive means the model underestimates the wave. Distinct from the ERA5 bias above — this is how good the forecast is, not how biased the reanalysis model is. Stats are split by platform: <strong className="text-fg">IH</strong> (Datawell buoys, keyed) vs <strong className="text-fg">WMO-ES</strong> (Copernicus, keyless) — the mixed total alone hides how each behaves.</>
              )}
            </p>
            {byOrigin.ih || byOrigin['wmo-es'] ? (
              <div className="flex flex-col sm:flex-row gap-3">
                {(['ih', 'wmo-es'] as const).map((origin) => {
                  const s = byOrigin[origin]
                  if (!s) return null
                  return (
                    <div
                      key={origin}
                      className="flex-1 rounded-lg border border-divider bg-surface-1/[0.03] px-4 py-3"
                      data-skill-origin={origin}
                    >
                      <p className="text-xs font-semibold uppercase tracking-wide text-fg-subtle">
                        {isPt
                          ? origin === 'ih'
                            ? 'Boias IH (Datawell)'
                            : 'Boias ES (Copernicus WMO)'
                          : origin === 'ih'
                            ? 'IH buoys (Datawell)'
                            : 'ES buoys (Copernicus WMO)'}
                      </p>
                      <p className="mt-1 text-sm text-fg tabular-nums">
                        n={s.n} · ME <span className="font-medium">{sign(s.me)}</span> m · MAE {two(s.mae)} m · RMSE {two(s.rmse)} m
                        {s.corr != null ? ` · r ${s.corr.toFixed(2)}` : ''}
                      </p>
                    </div>
                  )
                })}
              </div>
            ) : null}
            <div className="overflow-x-auto">
              <table className="w-full min-w-[480px] border-collapse text-meta">
                <thead>
                  <tr className="text-left text-xs uppercase tracking-wide text-fg-subtle">
                    <th className="py-1.5 pr-3 font-semibold">{isPt ? 'Boia' : 'Buoy'}</th>
                    <th className="py-1.5 pr-3 font-semibold">{isPt ? 'Origem' : 'Origin'}</th>
                    <th className="py-1.5 pr-3 text-right font-semibold">n</th>
                    <th className="py-1.5 pr-3 text-right font-semibold">ME (m)</th>
                    <th className="py-1.5 pr-3 text-right font-semibold">MAE (m)</th>
                    <th className="py-1.5 pr-3 text-right font-semibold">RMSE (m)</th>
                    <th className="py-1.5 pr-3 text-right font-semibold">r</th>
                    <th className="py-1.5 text-right font-semibold">
                      {isPt ? 'Lead médio (h)' : 'Mean lead (h)'}
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {skill.buoys.map((b) => (
                    <tr key={b.id} className="border-b border-divider last:border-0">
                      <td className="py-1.5 pr-3 font-medium text-fg">{b.name}</td>
                      <td className="py-1.5 pr-3 text-fg-muted">{originLabel(b.origin)}</td>
                      <td className="py-1.5 pr-3 text-right tabular-nums">{b.n}</td>
                      <td className="py-1.5 pr-3 text-right tabular-nums font-medium">{sign(b.me)}</td>
                      <td className="py-1.5 pr-3 text-right tabular-nums">{two(b.mae)}</td>
                      <td className="py-1.5 pr-3 text-right tabular-nums">{two(b.rmse)}</td>
                      <td className="py-1.5 pr-3 text-right tabular-nums text-fg-muted">{two(b.corr)}</td>
                      <td className="py-1.5 text-right tabular-nums text-fg-muted">{two(b.meanLeadHours)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="text-xs text-fg-subtle">
              {(() => {
                const byOrigin = skill.pairCountByOrigin ?? { ih: 0, 'wmo-es': 0 }
                const calib = skill.calibratedPairCount ?? 0
                const base = isPt
                  ? `Actualizado ${new Date(skill.fetchedAt ?? '').toLocaleDateString('pt-PT')} · ${skill.pairCount} pares previsto×medido acumulados · só boias com n≥10`
                  : `Updated ${new Date(skill.fetchedAt ?? '').toLocaleDateString('en-GB')} · ${skill.pairCount} accumulated forecast×observed pairs · buoys with n≥10 only`
                if (byOrigin.ih === 0 && byOrigin['wmo-es'] === 0) return base
                const perOrigin = isPt
                  ? `IH ${byOrigin.ih} · WMO-ES ${byOrigin['wmo-es']} pares`
                  : `IH ${byOrigin.ih} · WMO-ES ${byOrigin['wmo-es']} pairs`
                const calibNote =
                  calib > 0
                    ? isPt
                      ? ` · ${calib} da camada calibrada ES→PT (referência PT)`
                      : ` · ${calib} from the ES→PT calibrated layer (PT reference)`
                    : ''
                return `${base} · ${perOrigin}${calibNote}`
              })()}
            </p>
          </div>
        )
      })()}

      <WaveBiasSection isPt={isPt} />
      <CoherenceTrendSection isPt={isPt} />

      <div className="text-center space-y-4">
        <p className="flex items-center justify-center gap-2 text-fg-muted">
          <Heart className="w-5 h-5 text-windDir-onshore" />
          {isPt ? 'Feito com paixão pela comunidade náutica portuguesa' : 'Made with passion for the Portuguese nautical community'}
        </p>
        <Button
          href="https://github.com/braindeadpt/ventu"
          variant="secondary"
          size="lg"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Code className="w-5 h-5" aria-hidden />
          {isPt ? 'Contribuir no GitHub ↗' : 'Contribute on GitHub ↗'}
        </Button>
      </div>
    </div>
  )
}
