/**
 * VenTu — RSS 2.0 feed generator
 *
 * Reads public/data/news.json (produced by update-news.js) and emits:
 *   public/rss.xml    — PT feed (title/summary, links to /pt/news/{slug}/)
 *   public/rss-en.xml — EN feed (titleEn/summaryEn, links to /en/news/{slug}/)
 *
 * Same contract as generate-sitemap.js: generated file, committed to the
 * repo, regenerated by update-news.yml only when news.json changes.
 *
 * Deterministic output: no "now" timestamps anywhere — <lastBuildDate> is the
 * newest item's pubDate, so re-running on unchanged input is a byte-identical
 * no-op (keeps commits clean and any future drift check meaningful).
 */

const fs = require('fs');
const path = require('path');

const BASE_URL = 'https://ventu.surf';
const MAX_ITEMS = 50;

// Mirrors src/lib/news.ts — keep in sync (same contract the /news/[slug]/
// routes and generate-sitemap.js use to resolve article URLs).
function slugify(text) {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
}

function newsSlug(item) {
  const base = slugify(item.title);
  const hash = item.id.slice(-6);
  return `${base}-${hash}`;
}

function escapeXml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function toRfc822(iso) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toUTCString();
}

function buildFeed({ locale, feedFile, channelTitle, channelDescription, pickTitle, pickSummary }) {
  const newsPath = path.join(__dirname, '..', 'public', 'data', 'news.json');
  const items = JSON.parse(fs.readFileSync(newsPath, 'utf8'));

  const sorted = items
    .filter((it) => it && it.id && it.publishedAt)
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
    .slice(0, MAX_ITEMS);

  const lastBuild = sorted.length ? toRfc822(sorted[0].publishedAt) : null;

  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${escapeXml(channelTitle)}</title>
  <link>${BASE_URL}/${locale}/news/</link>
  <description>${escapeXml(channelDescription)}</description>
  <language>${locale === 'pt' ? 'pt-PT' : 'en'}</language>
  <atom:link href="${BASE_URL}/${feedFile}" rel="self" type="application/rss+xml" />
`;
  if (lastBuild) xml += `  <lastBuildDate>${lastBuild}</lastBuildDate>\n`;

  for (const item of sorted) {
    const title = pickTitle(item) || item.title;
    const description = pickSummary(item) || item.summary || '';
    const link = `${BASE_URL}/${locale}/news/${encodeURI(newsSlug(item))}/`;
    const pubDate = toRfc822(item.publishedAt);
    const sourceUrl = item.url && /^https?:\/\//.test(item.url) ? item.url : null;

    xml += `  <item>
    <title>${escapeXml(title)}</title>
    <link>${link}</link>
    <guid isPermaLink="false">${escapeXml(item.id)}</guid>
`;
    if (pubDate) xml += `    <pubDate>${pubDate}</pubDate>\n`;
    if (item.category) xml += `    <category>${escapeXml(item.category)}</category>\n`;
    if (description) xml += `    <description>${escapeXml(description)}</description>\n`;
    if (sourceUrl) xml += `    <source url="${escapeXml(sourceUrl)}">${escapeXml(item.source || '')}</source>\n`;
    xml += `  </item>\n`;
  }

  xml += `</channel>\n</rss>\n`;
  return xml;
}

const feeds = [
  {
    locale: 'pt',
    feedFile: 'rss.xml',
    channelTitle: 'VenTu — Notícias náuticas',
    channelDescription:
      'Notícias e condições para desportos náuticos em Portugal — surf, kitesurf, windsurf, foil e big wave.',
    pickTitle: (it) => it.title,
    pickSummary: (it) => it.summary,
  },
  {
    locale: 'en',
    feedFile: 'rss-en.xml',
    channelTitle: 'VenTu — Water sports news',
    channelDescription:
      'Water sports news and conditions in Portugal — surf, kitesurf, windsurf, foil and big wave.',
    pickTitle: (it) => it.titleEn || it.title,
    pickSummary: (it) => it.summaryEn || it.summary,
  },
];

for (const feed of feeds) {
  const xml = buildFeed(feed);
  const out = path.join(__dirname, '..', 'public', feed.feedFile);
  fs.writeFileSync(out, xml);
  const count = (xml.match(/<item>/g) || []).length;
  console.log(`✅ ${feed.feedFile}: ${count} items → ${out}`);
}
