// Novos spots para adicionar ao Ventu
// Gerado com pesquisa exaustiva de spots em Portugal continental

const newSpots = [
  // ===== NORTE =====
  {
    id: 'murtosa',
    slug: 'murtosa',
    name: 'Murtosa',
    nameEn: 'Murtosa',
    region: 'Aveiro',
    regionEn: 'Aveiro',
    lat: 40.733,
    lon: -8.650,
    coastOrientation: 270,
    type: 'kitesurf',
    difficulty: 'beginner',
    bestWind: 'NW, N',
    bestSwell: 'Rio',
    description: 'Laguna de água plana perfeita para kitesurf e windsurf. Vento térmico de NW consistente. Uma das melhores lagoas do centro de Portugal para iniciantes.',
    descriptionEn: 'Flat water lagoon perfect for kitesurfing and windsurfing. Consistent NW thermal wind. One of the best lagoons in central Portugal for beginners.',
    facilities: ['Estacionamento', 'Escola kite', 'WC'],
    hazards: ['Bancos de areia na maré baixa'],
    compatibleSports: ['kitesurf', 'windsurf', 'foil', 'sup'],
    blueFlag: true,
  },
  {
    id: 'furadouro',
    slug: 'furadouro',
    name: 'Furadouro',
    nameEn: 'Furadouro',
    region: 'Ovar',
    regionEn: 'Ovar',
    lat: 40.650,
    lon: -8.670,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia extensa com ondas consistentes e múltiplos picos. Beach break popular entre surfistas do Porto e Aveiro. Funciona em quase todas as marés.',
    descriptionEn: 'Extensive beach with consistent waves and multiple peaks. Popular beach break among Porto and Aveiro surfers. Works on almost all tides.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
    hazards: ['Correntes', 'Multidão no verão'],
    compatibleSports: ['surf', 'bodyboard'],
    blueFlag: true,
  },
  {
    id: 'figueira-foz',
    slug: 'figueira-foz',
    name: 'Figueira da Foz (Buarcos)',
    nameEn: 'Figueira da Foz (Buarcos)',
    region: 'Figueira da Foz',
    regionEn: 'Figueira da Foz',
    lat: 40.150,
    lon: -8.870,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Uma das praias mais emblemáticas do centro de Portugal. Ondas potentes e consistentes, palco de campeonatos nacionais. O molhe divide a praia em dois picos distintos.',
    descriptionEn: 'One of the most emblematic beaches in central Portugal. Powerful and consistent waves, host of national championships. The jetty divides the beach into two distinct peaks.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'Alojamento', 'WC'],
    hazards: ['Correntes fortes', 'Rochas junto ao molhe'],
    compatibleSports: ['surf', 'bodyboard'],
    blueFlag: true,
  },
  {
    id: 'quiaios',
    slug: 'quiaios',
    name: 'Quiaios',
    nameEn: 'Quiaios',
    region: 'Figueira da Foz',
    regionEn: 'Figueira da Foz',
    lat: 40.200,
    lon: -8.870,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'beginner',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia longa e selvagem no norte da Figueira da Foz. Ondas suaves ideais para iniciantes. Pouco crowd e ambiente natural preservado.',
    descriptionEn: 'Long and wild beach north of Figueira da Foz. Gentle waves ideal for beginners. Low crowd and preserved natural environment.',
    facilities: ['Estacionamento', 'WC'],
    hazards: ['Correntes moderadas', 'Sem vigilância'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'leirosa',
    slug: 'leirosa',
    name: 'Leirosa',
    nameEn: 'Leirosa',
    region: 'Figueira da Foz',
    regionEn: 'Figueira da Foz',
    lat: 39.850,
    lon: -8.900,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Praia rústica e pouco frequentada entre a Figueira da Foz e Nazaré. Beach break potente com ondas tubulares em dias bons. Para surfistas que gostam de isolamento.',
    descriptionEn: 'Rustic and little-frequented beach between Figueira da Foz and Nazaré. Powerful beach break with tubular waves on good days. For surfers who enjoy isolation.',
    facilities: ['Estacionamento'],
    hazards: ['Correntes fortes', 'Sem infraestruturas'],
    compatibleSports: ['surf', 'bodyboard'],
  },

  // ===== CENTRO / LISBOA =====
  {
    id: 'obidos-lagoon',
    slug: 'obidos-lagoon',
    name: 'Lagoa de Óbidos',
    nameEn: 'Obidos Lagoon',
    region: 'Óbidos',
    regionEn: 'Obidos',
    lat: 39.400,
    lon: -9.220,
    coastOrientation: 270,
    type: 'kitesurf',
    difficulty: 'beginner',
    bestWind: 'NW, N',
    bestSwell: 'Lagoa',
    description: 'A maior lagoa de água salgada de Portugal. Água plana e rasa, ideal para aprender kitesurf, windsurf, wing foil e SUP. Vento térmico de NW amplificado pelo efeito venturi. Uma das melhores escolas de Portugal.',
    descriptionEn: 'The largest saltwater lagoon in Portugal. Flat and shallow water, ideal for learning kitesurfing, windsurfing, wing foiling and SUP. NW thermal wind amplified by the venturi effect. One of the best schools in Portugal.',
    facilities: ['Estacionamento', 'Escolas kite', 'Escolas windsurf', 'Escolas wing foil', 'WC', 'Restaurantes'],
    hazards: ['Conchas no fundo', 'Bancos de areia na maré baixa'],
    compatibleSports: ['kitesurf', 'windsurf', 'foil', 'sup'],
    blueFlag: true,
    localTips: {
      bestTide: 'Maré média a alta para mais profundidade',
      bestTideEn: 'Mid to high tide for more depth',
      parking: 'Gratuito junto à lagoa',
      parkingEn: 'Free near the lagoon',
    },
  },
  {
    id: 'sao-lourenco',
    slug: 'sao-lourenco',
    name: 'São Lourenço (Ericeira)',
    nameEn: 'Sao Lourenco (Ericeira)',
    region: 'Ericeira',
    regionEn: 'Ericeira',
    lat: 38.980,
    lon: -9.420,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'N, NW',
    bestSwell: 'W, NW',
    description: 'O spot mais a norte da Reserva Mundial de Surf da Ericeira. Baía abrigada onde o vento de NW é cross-shore ou ligeiramente offshore. Direitas longas e potentes a partir de 1.5m. Excelente para intermediários.',
    descriptionEn: 'The northernmost spot of Ericeira World Surfing Reserve. Sheltered bay where NW wind is cross-shore or slightly offshore. Long and powerful rights from 1.5m. Excellent for intermediates.',
    facilities: ['Estacionamento', 'Restaurante', 'WC'],
    hazards: ['Rochas submersas', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'pedra-branca',
    slug: 'pedra-branca',
    name: 'Pedra Branca (Ericeira)',
    nameEn: 'Pedra Branca (Ericeira)',
    region: 'Ericeira',
    regionEn: 'Ericeira',
    lat: 38.975,
    lon: -9.415,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'advanced',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Reef break poderoso considerado irmão gémeo do Coxos. Ondas velozes, tubulares e frequentes. Um dos picos mais técnicos da Ericeira. Apenas para surfistas experientes.',
    descriptionEn: 'Powerful reef break considered twin brother of Coxos. Fast, tubular and frequent waves. One of the most technical peaks in Ericeira. For experienced surfers only.',
    facilities: ['Estacionamento'],
    hazards: ['Rochas', 'Ondas potentes', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'sao-sebastiao',
    slug: 'sao-sebastiao',
    name: 'São Sebastião (Ericeira)',
    nameEn: 'Sao Sebastiao (Ericeira)',
    region: 'Ericeira',
    regionEn: 'Ericeira',
    lat: 38.970,
    lon: -9.420,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia de surf mais acessível da Ericeira. Ondas desafiadoras mas gerenciáveis. Múltiplos picos ao longo da praia. Excelente para surfistas em evolução.',
    descriptionEn: 'Most accessible surf beach in Ericeira. Challenging but manageable waves. Multiple peaks along the beach. Excellent for evolving surfers.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
    hazards: ['Correntes', 'Rochas'],
    compatibleSports: ['surf', 'bodyboard'],
    blueFlag: true,
  },
  {
    id: 'empa',
    slug: 'empa',
    name: 'Praia da Empa (Ericeira)',
    nameEn: 'Praia da Empa (Ericeira)',
    region: 'Ericeira',
    regionEn: 'Ericeira',
    lat: 38.985,
    lon: -9.425,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'advanced',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Pequena praia com duas jóias: Pedra Branca e Reef. Ondas velozes e potentes que atraem bodyboarders e surfistas avançados ao longo do ano.',
    descriptionEn: 'Small beach with two gems: Pedra Branca and Reef. Fast and powerful waves that attract bodyboarders and advanced surfers year-round.',
    facilities: ['Estacionamento'],
    hazards: ['Rochas', 'Ondas tubulares', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'foz-sizandro',
    slug: 'foz-sizandro',
    name: 'Foz do Sizandro',
    nameEn: 'Foz do Sizandro',
    region: 'Torres Vedras',
    regionEn: 'Torres Vedras',
    lat: 39.080,
    lon: -9.350,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'beginner',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia familiar na foz do rio Sizandro. Ondas suaves e consistentes, perfeitas para iniciantes. Ambiente tranquilo e pouco crowd.',
    descriptionEn: 'Family beach at the mouth of the Sizandro river. Gentle and consistent waves, perfect for beginners. Tranquil atmosphere and low crowd.',
    facilities: ['Estacionamento', 'Restaurante', 'WC'],
    hazards: ['Correntes na foz'],
    compatibleSports: ['surf', 'bodyboard', 'sup'],
    blueFlag: true,
  },
  {
    id: 'sao-joao-caparica',
    slug: 'sao-joao-caparica',
    name: 'São João da Caparica',
    nameEn: 'Sao Joao da Caparica',
    region: 'Costa da Caparica',
    regionEn: 'Costa da Caparica',
    lat: 38.650,
    lon: -9.230,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'beginner',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia mais tranquila da Costa da Caparica. Ondas suaves ideais para aprender. Menos crowd que as praias centrais. Perfeita para famílias e iniciantes.',
    descriptionEn: 'Quieter beach at Costa da Caparica. Gentle waves ideal for learning. Less crowded than central beaches. Perfect for families and beginners.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
    hazards: ['Correntes moderadas'],
    compatibleSports: ['surf', 'bodyboard', 'sup'],
    blueFlag: true,
  },
  {
    id: 'nova-vaga',
    slug: 'nova-vaga',
    name: 'Nova Vaga (Costa da Caparica)',
    nameEn: 'Nova Vaga (Costa da Caparica)',
    region: 'Costa da Caparica',
    regionEn: 'Costa da Caparica',
    lat: 38.660,
    lon: -9.240,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Um dos picos mais consistentes da Costa da Caparica. Múltiplos peaks com ondas de qualidade. Muito procurada por surfistas de Lisboa.',
    descriptionEn: 'One of the most consistent peaks at Costa da Caparica. Multiple peaks with quality waves. Very popular among Lisbon surfers.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurante', 'WC'],
    hazards: ['Correntes', 'Multidão'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'parede',
    slug: 'parede',
    name: 'Parede',
    nameEn: 'Parede',
    region: 'Cascais',
    regionEn: 'Cascais',
    lat: 38.680,
    lon: -9.350,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia rochosa entre Carcavelos e São Pedro. Ondas rápidas e tubulares em dias de swell. Palco de competições de bodyboard.',
    descriptionEn: 'Rocky beach between Carcavelos and Sao Pedro. Fast and tubular waves on swell days. Host of bodyboarding competitions.',
    facilities: ['Estacionamento', 'Restaurante', 'WC'],
    hazards: ['Rochas', 'Ondas rápidas'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'praia-grande-sintra',
    slug: 'praia-grande-sintra',
    name: 'Praia Grande (Sintra)',
    nameEn: 'Praia Grande (Sintra)',
    region: 'Sintra',
    regionEn: 'Sintra',
    lat: 38.820,
    lon: -9.470,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Extensa praia entre falésias, famosa pelo bodyboard e surf. Palco do Mundial de Bodyboard. Ondas potentes com múltiplos picos. Uma das praias mais bonitas da linha de Sintra.',
    descriptionEn: 'Extensive beach between cliffs, famous for bodyboarding and surfing. Host of the World Bodyboard Championship. Powerful waves with multiple peaks. One of the most beautiful beaches on the Sintra coast.',
    facilities: ['Estacionamento', 'Escola surf', 'Restaurantes', 'WC'],
    hazards: ['Correntes fortes', 'Rochas submersas'],
    compatibleSports: ['surf', 'bodyboard'],
    blueFlag: true,
  },
  {
    id: 'adraga',
    slug: 'adraga',
    name: 'Praia da Adraga',
    nameEn: 'Adraga Beach',
    region: 'Sintra',
    regionEn: 'Sintra',
    lat: 38.790,
    lon: -9.490,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'advanced',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia selvagem entre falésias dramáticas. Ondas potentes e tubulares. Spot avançado com cenário de cortar a respiração. Uma das praias mais fotografadas de Portugal.',
    descriptionEn: 'Wild beach between dramatic cliffs. Powerful and tubular waves. Advanced spot with breathtaking scenery. One of the most photographed beaches in Portugal.',
    facilities: ['Estacionamento', 'Restaurante'],
    hazards: ['Rochas', 'Ondas potentes', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
  },

  // ===== ALENTEJO =====
  {
    id: 'amoreira',
    slug: 'amoreira',
    name: 'Praia da Amoreira',
    nameEn: 'Amoreira Beach',
    region: 'Aljezur',
    regionEn: 'Aljezur',
    lat: 37.350,
    lon: -8.850,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Praia deslumbrante onde o rio Aljezur encontra o Atlântico. Dunas, falésias e uma lagoa perfeita para SUP. Ondas consistentes com múltiplos picos. Um dos spots mais bonitos da Costa Vicentina.',
    descriptionEn: 'Stunning beach where the Aljezur river meets the Atlantic. Dunes, cliffs and a perfect lagoon for SUP. Consistent waves with multiple peaks. One of the most beautiful spots on the Vicentina Coast.',
    facilities: ['Estacionamento', 'Restaurante', 'WC'],
    hazards: ['Correntes na foz do rio', 'Rochas'],
    compatibleSports: ['surf', 'kitesurf', 'sup'],
    blueFlag: true,
  },
  {
    id: 'monte-clerigo',
    slug: 'monte-clerigo',
    name: 'Monte Clérigo',
    nameEn: 'Monte Clerigo',
    region: 'Aljezur',
    regionEn: 'Aljezur',
    lat: 37.340,
    lon: -8.860,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Praia de vila piscatória com ambiente boémio. Picos shiftantes que quando alinham oferecem ondas divertidas. Ótima para famílias e surfistas em evolução.',
    descriptionEn: 'Fishing village beach with bohemian atmosphere. Shifty peaks that when aligned offer fun waves. Great for families and evolving surfers.',
    facilities: ['Estacionamento', 'Restaurantes', 'WC'],
    hazards: ['Rochas na maré baixa', 'Bancos de areia mutáveis'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'vale-figueiras',
    slug: 'vale-figueiras',
    name: 'Vale Figueiras',
    nameEn: 'Vale Figueiras',
    region: 'Aljezur',
    regionEn: 'Aljezur',
    lat: 37.250,
    lon: -8.850,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Praia selvagem no Parque Natural do Sudoeste Alentejano. Ondas para todos os níveis dependendo das condições. Acesso por estrada de terra. Isolamento total.',
    descriptionEn: 'Wild beach in the Southwest Alentejo Natural Park. Waves for all levels depending on conditions. Dirt road access. Total isolation.',
    facilities: ['Estacionamento'],
    hazards: ['Sem vigilância', 'Acesso difícil'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'amado',
    slug: 'amado',
    name: 'Praia do Amado',
    nameEn: 'Amado Beach',
    region: 'Carrapateira',
    regionEn: 'Carrapateira',
    lat: 37.180,
    lon: -8.900,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, NE',
    bestSwell: 'W, NW',
    description: 'Um dos spots mais consistentes e famosos do Algarve. Três picos principais visíveis do miradouro. Ondas potentes com muitos surfistas de várias nacionalidades no verão. Acesso fácil e infraestruturas.',
    descriptionEn: 'One of the most consistent and famous spots in the Algarve. Three main peaks visible from the viewpoint. Powerful waves with many surfers of various nationalities in summer. Easy access and infrastructure.',
    facilities: ['Estacionamento', 'Escolas surf', 'Restaurantes', 'WC'],
    hazards: ['Correntes', 'Ondas potentes', 'Multidão no verão'],
    compatibleSports: ['surf', 'bodyboard', 'sup'],
    blueFlag: true,
  },
  {
    id: 'cordoama',
    slug: 'cordoama',
    name: 'Cordoama',
    nameEn: 'Cordoama',
    region: 'Vila do Bispo',
    regionEn: 'Vila do Bispo',
    lat: 37.080,
    lon: -8.950,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Spot flanqueado por falésias imponentes. Um dos mais consistentes da região, palco do circuito mundial WQS. Bancos de areia bem colocados. Menos massificado que o Amado.',
    descriptionEn: 'Spot flanked by imposing cliffs. One of the most consistent in the region, host of the WQS world circuit. Well-placed sandbanks. Less crowded than Amado.',
    facilities: ['Estacionamento', 'Restaurante'],
    hazards: ['Rochas', 'Correntes', 'Exposição ao vento'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'castelejo',
    slug: 'castelejo',
    name: 'Castelejo',
    nameEn: 'Castelejo',
    region: 'Vila do Bispo',
    regionEn: 'Vila do Bispo',
    lat: 37.090,
    lon: -8.960,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'advanced',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia selvagem com ondas potentes e tubulares. Spot avançado com fundo de areia e rochas. Cenário dramático com falésias negras.',
    descriptionEn: 'Wild beach with powerful and tubular waves. Advanced spot with sand and rock bottom. Dramatic scenery with black cliffs.',
    facilities: ['Estacionamento'],
    hazards: ['Rochas', 'Ondas potentes', 'Correntes fortes'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'barriga',
    slug: 'barriga',
    name: 'Barriga',
    nameEn: 'Barriga',
    region: 'Vila do Bispo',
    regionEn: 'Vila do Bispo',
    lat: 37.100,
    lon: -8.930,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia isolada a norte da Cordoama. Ondas de qualidade quando os bancos alinham. Pouco crowd e ambiente natural preservado. Acesso a pé na maré baixa.',
    descriptionEn: 'Isolated beach north of Cordoama. Quality waves when the banks align. Low crowd and preserved natural environment. Foot access at low tide.',
    facilities: [],
    hazards: ['Sem infraestruturas', 'Acesso difícil', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
  },
  {
    id: 'alteirinhos',
    slug: 'alteirinhos',
    name: 'Alteirinhos',
    nameEn: 'Alteirinhos',
    region: 'Zambujeira do Mar',
    regionEn: 'Zambujeira do Mar',
    lat: 37.650,
    lon: -8.780,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia selvagem ao sul da Zambujeira do Mar. Acesso por escadaria na falésia. Areia fina, falésias altas e mar transparente. Perfeita para quem quer fugir das multidões.',
    descriptionEn: 'Wild beach south of Zambujeira do Mar. Access by staircase in the cliff. Fine sand, high cliffs and transparent sea. Perfect for those who want to escape the crowds.',
    facilities: ['Estacionamento'],
    hazards: ['Escadaria íngreme', 'Sem vigilância'],
    compatibleSports: ['surf', 'bodyboard'],
  },

  // ===== ALGARVE =====
  {
    id: 'luz',
    slug: 'luz',
    name: 'Praia da Luz',
    nameEn: 'Praia da Luz',
    region: 'Lagos',
    regionEn: 'Lagos',
    lat: 37.090,
    lon: -8.720,
    coastOrientation: 270,
    type: 'surf',
    difficulty: 'intermediate',
    bestWind: 'E, SE',
    bestSwell: 'W, NW',
    description: 'Praia familiar que esconde um reef break de qualidade junto à Rocha Negra. Direitas perfeitas com a maré e swell certos. Pouco conhecida fora da comunidade local.',
    descriptionEn: 'Family beach that hides a quality reef break near Rocha Negra. Perfect rights with the right tide and swell. Little known outside the local community.',
    facilities: ['Estacionamento', 'Restaurantes', 'Alojamento', 'WC'],
    hazards: ['Rochas', 'Correntes'],
    compatibleSports: ['surf', 'bodyboard'],
    blueFlag: true,
  },
  {
    id: 'burgau',
    slug: 'burgau',
    name: 'Burgau',
    nameEn: 'Burgau',
    region: 'Vila do Bispo',
    regionEn: 'Vila do Bispo',
    lat: 37.070,
    lon: -8.780,
    coastOrientation: 180,
    type: 'surf',
    difficulty: 'beginner',
    bestWind: 'N, NW',
    bestSwell: 'S, SW',
    description: 'Aldeia piscatória autêntica com point break nas duas pontas da baía. Ambiente familiar e água cristalina. Quando funciona, transforma-se numa pequena piscina de ondas.',
    descriptionEn: 'Authentic fishing village with point break on both ends of the bay. Family atmosphere and crystal clear water. When it works, it transforms into a small wave pool.',
    facilities: ['Estacionamento', 'Restaurantes', 'WC'],
    hazards: ['Rochas nas pontas'],
    compatibleSports: ['surf', 'bodyboard', 'sup'],
  },
  {
    id: 'salema',
    slug: 'salema',
    name: 'Salema',
    nameEn: 'Salema',
    region: 'Vila do Bispo',
    regionEn: 'Vila do Bispo',
    lat: 37.060,
    lon: -8.820,
    coastOrientation: 180,
    type: 'surf',
    difficulty: 'beginner',
    bestWind: 'N, NW',
    bestSwell: 'S, SW',
    description: 'Praia de vila piscatória no coração do Algarve. Ondas suaves ideais para iniciantes e longboarders. Água cristalina e ambiente tranquilo.',
    descriptionEn: 'Fishing village beach in the heart of the Algarve. Gentle waves ideal for beginners and longboarders. Crystal clear water and tranquil atmosphere.',
    facilities: ['Estacionamento', 'Restaurantes', 'Alojamento', 'WC'],
    hazards: ['Rochas submersas'],
    compatibleSports: ['surf', 'sup'],
    blueFlag: true,
  },
  {
    id: 'bordeira',
    slug: 'bordeira',
    name: 'Praia da Bordeira',
    nameEn: 'Bordeira Beach',
    region: 'Carrapateira',
    regionEn: 'Carrapateira',
    lat: 37.200,
    lon: -8.900,
    coastOrientation: 270,
    type: 'kitesurf',
    difficulty: 'advanced',
    bestWind: 'N, NW',
    bestSwell: 'W, NW',
    description: 'Ondas enormes no inverno, lagoon plana no verão. Um dos spots mais versáteis do Algarve para kitesurf e surf. Vento cross-onshore consistente.',
    descriptionEn: 'Huge waves in winter, flat lagoon in summer. One of the most versatile spots in the Algarve for kitesurfing and surfing. Consistent cross-onshore wind.',
    facilities: ['Estacionamento'],
    hazards: ['Ondas gigantes no inverno', 'Correntes'],
    compatibleSports: ['kitesurf', 'surf', 'bodyboard'],
  },
  {
    id: 'fuseta',
    slug: 'fuseta',
    name: 'Fuseta',
    nameEn: 'Fuseta',
    region: 'Olhão',
    regionEn: 'Olhao',
    lat: 37.050,
    lon: -7.750,
    coastOrientation: 180,
    type: 'kitesurf',
    difficulty: 'beginner',
    bestWind: 'SW, W',
    bestSwell: 'Lagoa',
    description: 'Laguna calma na Ria Formosa, alternativa menos concorrida que Alvor. Funciona na maré alta. Vento térmico consistente no verão. Água quente e plana perfeita para iniciantes.',
    descriptionEn: 'Calm lagoon in Ria Formosa, less crowded alternative to Alvor. Works at high tide. Consistent thermal wind in summer. Warm and flat water perfect for beginners.',
    facilities: ['Estacionamento', 'Escola kite', 'WC'],
    hazards: ['Bancos de areia na maré baixa', 'Balsa de barcos'],
    compatibleSports: ['kitesurf', 'wing foil', 'sup'],
  },
  {
    id: 'ilha-faro',
    slug: 'ilha-faro',
    name: 'Ilha de Faro',
    nameEn: 'Faro Island',
    region: 'Faro',
    regionEn: 'Faro',
    lat: 36.980,
    lon: -7.980,
    coastOrientation: 180,
    type: 'kitesurf',
    difficulty: 'intermediate',
    bestWind: 'NW, N',
    bestSwell: 'Lagoa',
    description: 'Ilha na Ria Formosa com lagoon de água plana e praia oceânica. Kitesurf na lagoon, SUP na calma do estuário. Flamingos e natureza intocada.',
    descriptionEn: 'Island in Ria Formosa with flat water lagoon and ocean beach. Kitesurfing in the lagoon, SUP in the calm estuary. Flamingos and untouched nature.',
    facilities: ['Estacionamento', 'Barco para a ilha', 'WC'],
    hazards: ['Corredores de barcos', 'Bancos de areia'],
    compatibleSports: ['kitesurf', 'sup'],
  },
  {
    id: 'ilha-tavira',
    slug: 'ilha-tavira',
    name: 'Ilha de Tavira',
    nameEn: 'Tavira Island',
    region: 'Tavira',
    regionEn: 'Tavira',
    lat: 37.120,
    lon: -7.650,
    coastOrientation: 180,
    type: 'kitesurf',
    difficulty: 'intermediate',
    bestWind: 'NW, N',
    bestSwell: 'Lagoa',
    description: '11km de duna com praia oceânica e lagoon. Ondas suaves na praia e água plana na Ria Formosa. Acessível de barco. Um dos melhores spots do Algarve oriental.',
    descriptionEn: '11km of dune with ocean beach and lagoon. Gentle waves on the beach and flat water in Ria Formosa. Accessible by boat. One of the best spots in eastern Algarve.',
    facilities: ['Barco para a ilha', 'Restaurantes', 'WC'],
    hazards: ['Acesso limitado', 'Correntes na foz'],
    compatibleSports: ['kitesurf', 'surf', 'sup'],
  },
  {
    id: 'cabanas-tavira',
    slug: 'cabanas-tavira',
    name: 'Cabanas de Tavira',
    nameEn: 'Cabanas de Tavira',
    region: 'Tavira',
    regionEn: 'Tavira',
    lat: 37.130,
    lon: -7.600,
    coastOrientation: 180,
    type: 'kitesurf',
    difficulty: 'beginner',
    bestWind: 'NW, N',
    bestSwell: 'Lagoa',
    description: 'Praia larga de areia dourada na Ria Formosa. Kitesurf na lagoon no inverno e na ilha o ano todo. Pouco crowd e vento consistente.',
    descriptionEn: 'Wide golden sand beach in Ria Formosa. Kitesurfing in the lagoon in winter and on the island year-round. Low crowd and consistent wind.',
    facilities: ['Estacionamento', 'Barco para a ilha', 'Restaurantes', 'WC'],
    hazards: ['Bancos de areia'],
    compatibleSports: ['kitesurf', 'sup'],
  },
  {
    id: 'ferragudo',
    slug: 'ferragudo',
    name: 'Praia Grande de Ferragudo',
    nameEn: 'Praia Grande de Ferragudo',
    region: 'Lagoa',
    regionEn: 'Lagoa',
    lat: 37.120,
    lon: -8.520,
    coastOrientation: 180,
    type: 'windsurf',
    difficulty: 'intermediate',
    bestWind: 'SE, E',
    bestSwell: 'S, SW',
    description: 'Excelente spot de wing foil e windsurf no inverno com o vento Levante (SE). Ondas rolantes na baía. Cenário pitoresco com o castelo de Ferragudo ao fundo.',
    descriptionEn: 'Excellent wing foiling and windsurfing spot in winter with Levante wind (SE). Rolling waves in the bay. Picturesque scenery with Ferragudo castle in the background.',
    facilities: ['Estacionamento', 'Restaurantes', 'WC'],
    hazards: ['Correntes na foz do rio', 'Bancos de areia'],
    compatibleSports: ['windsurf', 'foil', 'kitesurf'],
  },
];

module.exports = { newSpots };
